apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: bicycles.demos.fabric8.io
spec:
  group: demos.fabric8.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                cadence:
                  type: integer
                gear:
                  type: integer
                speed:
                  type: integer
                modelName:
                  type: string
            status:
              type: object
              properties:
                isInUse:
                  type: boolean 
      subresources:
        status: {}            
    - name: v1beta1
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                cadence:
                  type: integer
                gear:
                  type: integer
                speed:
                  type: integer
                modelName:
                  type: string
            status:
              type: object
              properties:
                isInUse:
                  type: boolean 
      subresources:
        status: {}            
  scope: Cluster
  names:
    plural: bicycles
    singular: bicycle
    kind: Bicycle
    shortNames:
    - bicycle
