apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: dummies.demo.fabric8.io
spec:
  group: demo.fabric8.io
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
  names:
    kind: Dummy
    plural: dummies
    shortNames:
    - dummy
