apiVersion: v1
kind: Pod
metadata:
  name: testpod
  labels:
    app: website
    role: frontend
spec:
  containers:
    - name: website
      image: nginx:1.7.9
      ports:
        - containerPort: 80
