apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: random-generator
spec:
  rules:
  - host: srva.example.com
    http:
      paths:
      - backend:
          serviceName: random-generator
          servicePort: 8080
