apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: satellites.demos.fabric8.io
spec:
  group: demos.fabric8.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                planet:
                  type: string
                mass:
                  type: string
                radius:
                  type: string
            status:
              type: object
              properties:
                orbitalPeriod:
                  type: string  
      subresources:
        status: {}            
  scope: Cluster
  names:
    plural: satellites
    singular: satellite
    kind: Satellite
    shortNames:
    - satellite
