---
apiVersion: v1
kind: Service
metadata:
  name: service-wait-until-ready
spec:
  selector:
    app: service-wait-until-ready
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: service-wait-until-ready
  labels:
    app: service-wait-until-ready
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "36000"]
      ports:
      - containerPort: 8080
        name: http
        protocol: TCP
