apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: 2019-06-20T13:11:34Z
  generation: 1
  name: sparkapplications.sparkoperator.k8s.io
  resourceVersion: "19931"
  selfLink: /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/sparkapplications.sparkoperator.k8s.io
  uid: edb28699-935c-11e9-b4dd-0800278bfe0a
spec:
  conversion:
    strategy: None
  group: sparkoperator.k8s.io
  names:
    kind: SparkApplication
    listKind: SparkApplicationList
    plural: sparkapplications
    shortNames:
    - sparkapp
    singular: sparkapplication
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        metadata:
          properties:
            name:
              maxLength: 63
              minLength: 1
              type: string
        spec:
          properties:
            arguments:
              items:
                type: string
              type: array
            deps:
              properties:
                downloadTimeout:
                  minimum: 1
                  type: integer
                maxSimultaneousDownloads:
                  minimum: 1
                  type: integer
            driver:
              properties:
                cores:
                  exclusiveMinimum: true
                  minimum: 0
                  type: number
                podName:
                  pattern: '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'
            executor:
              properties:
                cores:
                  exclusiveMinimum: true
                  minimum: 0
                  type: number
                instances:
                  minimum: 1
                  type: integer
            failureRetries:
              type: integer
            hadoopConf:
              type: object
            hadoopConfigMap:
              type: string
            image:
              type: string
            imagePullPolicy:
              enum:
              - Raw: Always
              - Raw: Never
              - Raw: IfNotPresent
            imagePullSecrets:
              items:
                type: string
              type: array
            initContainerImage:
              type: string
            mainApplicationFile:
              type: string
            mainClass:
              type: string
            memoryOverheadFactor:
              type: string
            mode:
              enum:
              - Raw: cluster
              - Raw: client
            monitoring:
              properties:
                exposeDriverMetrics:
                  type: boolean
                exposeExecutorMetrics:
                  type: boolean
                metricsProperties:
                  type: string
                prometheus:
                  properties:
                    port:
                      maximum: 49151
                      minimum: 1024
                      type: integer
            nodeSelector:
              type: object
            pythonVersion:
              enum:
              - Raw: "2"
              - Raw: "3"
            restartPolicy:
              properties:
                onFailureRetries:
                  minimum: 0
                  type: integer
                onFailureRetryInterval:
                  minimum: 1
                  type: integer
                onSubmissionFailureRetries:
                  minimum: 0
                  type: integer
                onSubmissionFailureRetryInterval:
                  minimum: 1
                  type: integer
                type:
                  enum:
                  - Raw: Never
                  - Raw: OnFailure
                  - Raw: Always
            retryInterval:
              type: integer
            sparkConf:
              type: object
            sparkConfigMap:
              type: string
            sparkVersion:
              type: string
            type:
              enum:
              - Raw: Java
              - Raw: Scala
              - Raw: Python
              - Raw: R
            volumes:
              items:
                properties:
                  name:
                    type: string
                type: object
              type: array
          required:
          - type
          - sparkVersion
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
status:
  acceptedNames:
    kind: SparkApplication
    listKind: SparkApplicationList
    plural: sparkapplications
    shortNames:
    - sparkapp
    singular: sparkapplication
  conditions:
  - lastTransitionTime: 2019-06-20T13:11:34Z
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: null
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1beta1

