apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  - name: c1
    image: nginx:1.19.2
    ports:
    - containerPort: 80  
  - name: c2
    image: alpine:3.12
    command: ["watch", "wget", "-qO-", "localhost"]
