apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: test-rs-multi
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: soaktestrs
  template:
    metadata:
      labels:
        app: soaktestrs
        environment: dev
    spec:
      containers:
      - name: soaktestrs
        image: nickchase/soaktest
        ports:
        - containerPort: 80
      - name: php-redis
        image: gcr.io/google_samples/gb-frontend:v3  
      - name: tomcat
        image: tomcat:8.0
        ports:
        - containerPort: 7474  
