---
apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  name: "widgets.test.fabric8.io"
spec:
  group: "test.fabric8.io"
  names:
    kind: "Widget"
    listKind: "WidgetList"
    plural: "widgets"
    singular: "widget"
  preserveUnknownFields: false
  scope: "Namespaced"
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            builderName:
              example: "builder-example"
              pattern: "^builder-"
              type: "string"
            edges:
              type: "integer"
            hollow:
              type: "boolean"
            dimensions:
              properties:
                x:
                  maximum: 100.0
                  minimum: 0.0
                  type: "integer"
                y:
                  maximum: 100.0
                  minimum: 0.0
                  type: "integer"
                zoom:
                  type: "boolean"
              type: "object"
            edgeTemplates:
              items:
                JSONSchemas: []
                type: "object"
                properties:
                  name:
                    type: "string"
                    pattern: "^edge-"
                  spiky:
                    type: "boolean"
              type: "array"
          required:
          - "builderName"
          - "edges"
          - "dimensions"
          type: "object"
      type: "object"
  version: "v1"
  versions:
  - name: "v1"
    served: true
    storage: true
